### ISSUE TITLE
one question about connect error.

### ISSUE THREAD

**Issue by albertcsg** [yscGit/CSSocketDemo#1]
您好，首先非常感谢您博客里的讲解，让我加深了对socket的理解。我在运行demo的时候遇到了一个问题，我连接6666端口不成功，猜测是没有打开，于是换成1080端口，显示连接成功，然而发送数据的时候终端不显示数据。请问，这是为什么呢？

**Comment by yangsanchao** [comment]
非常感谢关注到；
因为S端在PC机，所以需要用模拟器来测试：
测试的步骤：
1、监听 6666（这个是我在程序里给的默认监听端口）端口 ： 打开终端：输入 nc -lk 6666；
2、点击  connettion；
3、发送socket；服务器接收到socket；
4、服务端send ：hello socket；

**Comment by albertcsg** [comment]
谢谢。我之前是在真机上测试的，所以“127.0.0.1”已经不是电脑本机了，监听端口当然不会有数据啦。
